"""Initial table creation

Revision ID: 021fd30ba8a8
Revises: 663de8bbd563
Create Date: 2026-05-01 16:13:34.909164

"""

# revision identifiers, used by Alembic.
revision = '021fd30ba8a8'
down_revision = '663de8bbd563'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
