"""update_user_session

Revision ID: 1be80caf7f0a
Revises: 8de8d8168688
Create Date: 2026-04-28 01:46:36.931499

"""

# revision identifiers, used by Alembic.
revision = '1be80caf7f0a'
down_revision = '8de8d8168688'
branch_labels = None
depends_on = None

import sqlalchemy as sa
from alembic import op, context


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    schema = context.public_schema
    op.add_column('users', sa.Column('session_id', sa.String(length=256), nullable=True), schema=schema)
    op.add_column('users', sa.Column('multi_device', sa.SmallInteger(), nullable=True), schema=schema)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    schema = context.public_schema
    op.drop_column('users', 'multi_device', schema=schema)
    op.drop_column('users', 'session_id', schema=schema)
    # ### end Alembic commands ###
