"""text_printer init

Revision ID: 663de8bbd563
Revises: 1be80caf7f0a
Create Date: 2026-04-30 04:55:03.400917

"""

# revision identifiers, used by Alembic.
revision = '663de8bbd563'
down_revision = '1be80caf7f0a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_printers',
    sa.Column('is_epson', sa.Integer(), nullable=True),
    sa.Column('queue', sa.String(length=16), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('nama', sa.String(length=128), nullable=False),
    sa.Column('kode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('create_uid', sa.Integer(), nullable=True),
    sa.Column('update_uid', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_text_printers')),
    # schema='public'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_printers', ) #schema='public')
    # ### end Alembic commands ###
