"""tambah user id pada text-printers

Revision ID: 975f107434c6
Revises: 021fd30ba8a8
Create Date: 2026-05-05 14:04:05.260742

"""

# revision identifiers, used by Alembic.
revision = '975f107434c6'
down_revision = '021fd30ba8a8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_printers', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text_printers', 'user_id')
    # ### end Alembic commands ###
