"""Initial table creation

Revision ID: ab49cd111a36
Revises: 975f107434c6
Create Date: 2026-05-08 18:24:44.507154

"""

# revision identifiers, used by Alembic.
revision = 'ab49cd111a36'
down_revision = '975f107434c6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('text_printers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('text_printers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
