"""Initial table creation

Revision ID: d2dc53a168c8
Revises: 1be80caf7f0a
Create Date: 2026-04-30 01:39:46.558393

"""

# revision identifiers, used by Alembic.
revision = 'd2dc53a168c8'
down_revision = '1be80caf7f0a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_printers',
    sa.Column('nama', sa.String(length=128), nullable=False),
    sa.Column('kode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('create_uid', sa.Integer(), nullable=True),
    sa.Column('update_uid', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_text_printers')),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_printers', schema='public')
    # ### end Alembic commands ###
