[app:main]
use = egg:opensipkd_base
reload_templates = true
devel = true
debug_authorization = false
debug_notfound = false
debug_routematch = false
debug_templates = true
default_locale_name = en

sqlalchemy.url = postgresql://user:pass@localhost/db
sqlalchemy.echo = true

pyramid.includes =
    pyramid_tm
    pyramid_beaker
    pyramid_chameleon
    pyramid_rpc.jsonrpc

session.type = ext:database
session.secret = s0s3cr3t
session.cookie_expires = true
session.key = WhatEver
session.url = postgresql://user:pass@localhost/db
session.timeout = 3000
session.lock_dir = %(here)s/tmp

timezone = Asia/Jakarta
localization = id_ID.UTF-8
#localization = Indonesian_indonesia.1252
#localization = English_Australia.1252

static_files = %(here)s/../files
captcha_files = %(here)s/tmp/captcha
company = Opensipkd
ibukota   = Bekasi
departement = IT
address_1 = Jalan....
address_2 = Bekasi ...

center.phone = 021123456789
center.mobile = 081311045668
center.email = aa.gustiana@gmail.com
center.email_password =
center.smtp_server = 

_host = 

unoconv_py = C:\Program Files\LibreOffice 5\program\python.exe
unoconv_bin = C:\project\toko\env\Scripts\unoconv

modules = 
menus =

app_name = Base Opensipkd.com
allow_register = False

change_unit = False
departemen_chg_id = 3


[server:main]
use = egg:waitress#main
host = 0.0.0.0
port = 6543

# Begin logging configuration

[loggers]
keys = root, opensipkd, sqlalchemy

[handlers]
keys = console, filelog, tabel

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console, filelog, tabel

[logger_opensipkd]
level = INFO
handlers = 
qualname = opensipkd 

[logger_sqlalchemy]
level = WARN
handlers = 
qualname = sqlalchemy.engine
# "level = INFO" logs SQL queries.
# "level = DEBUG" logs SQL queries and results.
# "level = WARN" logs neither.  (Recommended for production systems.)

[handler_filelog]
class = FileHandler
args = ('/home/aagusti/log/web.log','a')
level = INFO
formatter = generic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[handler_tabel]
class = opensipkd.base.handlers.SQLAlchemyHandler
args = ()
level = WARN
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s][%(threadName)s] %(message)s

[alembic_base]
script_location = opensipkd.base:alembic
