[build-system]
requires = ['setuptools >= 64', 'wheel']
build-backend = 'setuptools.build_meta'

[tool.setuptools]
packages = ["opensipkd", "opensipkd.detable", "opensipkd.base"]

#[tool.setuptools.package-dir]
# mypkg = "lib"
#"opensipkd.models" = "models"
#"opensipkd.base" = "base"

[tool.mypy]
exclude = [
    'bak',
]
show_error_codes = true

[project]
name = 'opensipkd_base'
version = '5.0'
dependencies = [
    'sqlalchemy',
    'colander',
    'pyramid',
    'pyramid_tm',
    "pyramid_beaker",
    "pyramid_mailer",
    'SQLAlchemy',
    'transaction',
    'waitress',
    'ziggurat-foundations',
    'zope.sqlalchemy',
    'pytz',
    'deform',
    'psycopg2-binary',
    'pyramid_chameleon',
    'pyramid_rpc',
    'requests',
    'sqlalchemy-datatables',
    #'py3o.template',
    'wheezy.captcha',
    #'icecream',
    'google-api-python-client',
    'google',
    #'pyjwt',
    ]
requires-python = '>= 3.8'

authors = [
    {name='Agus Gustiana', email='aa.gustiana@gmail.com'},
    { email = "opensipkd@gmail.com" },]

maintainers = [
    { name = "Ari", email = "ariagungprasetiyo@gmail.com" },
    { name = "Owo Sugiana", email = "sugiana@gmail.com" }]

description = 'Framwork Aplikasi openSIPKD'
readme = 'README.rst'
# license = {text = 'Apache Software License'}
keywords = ["openSIPKD"]
classifiers = [
    'Development Status :: 5 - Beta',
    'Programming Language :: Python :: 3',
    'Operating System :: OS Independent',
    'Framework :: Pylons',
    'Topic :: Internet :: WWW/HTTP',
    'Topic :: Internet :: WWW/HTTP :: WSGI :: Application',
]

[project.optional-dependencies]
dev = [
    'pyramid_debugtoolbar',
    'pytest', 'webtest']

[project.entry-points."paste.app_factory"]
main = 'opensipkd.base:main'

[project.scripts]
osipkd-db-init = 'opensipkd.base.scripts.initializedb:main'
