# kode, path, nama
routes = [
    # ("user-area", "/user/area", "User Area"),
    # ("user-area-add", "/user/area/add", "Tambah User Area"),
    # ("user-area-edit", "/user/area/{id}/edit", "Edit User Area"),
    # ("user-area-delete", "/user/area/{id}/delete", "Hapus User Area"),
    # ("user-area-view", "/user/area/{id}/view", "Lihat User Area"),
    # ("user-area-act", "/user/area/{act}/act", "Action User Area"),
    # ("user-area-upload", "/user/area/upload", "Upload User Area"),
    # ("user-departemen", "/user/departemen", "User Departemen"),
    # ("user-departemen-add", "/user/departemen/add", "Tambah User Departemen"),
    # ("user-departemen-edit",
    #  "/user/departemen/{id}/edit", "Edit User Departemen"),
    # ("user-departemen-delete",
    #  "/user/departemen/{id}/delete", "Hapus User Departemen"),
    # ("user-departemen-view",
    #  "/user/departemen/{id}/view", "Lihat User Departemen"),
    # ("user-departemen-act",
    #  "/user/departemen/{act}/act", "Action User Departemen"),
    # ("user-departemen-upload", "/user/departemen/upload", "Upload User Departemen"),
]
