###
# app configuration
# http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/environment.html
###


;Digunakan untuk setting sebagai app:main atau app:virdir (virtual directory)
[app:main]
;[app:virdir] 
use = egg:opensipkd_base
reload_templates = true
pyramid.debug_all = true
pyramid.debug_authorization = false
pyramid.debug_notfound = true
pyramid.debug_routematch = true
pyramid.debug_templates = true
default_locale_name = id
sqlalchemy.url = postgresql://user:pass@server:port/db
sqlalchemy.pool_pre_ping = True
sqlalchemy.pool_size = 20
sqlalchemy.echo = False
session.url = postgresql://user:pass@server:port/db
pyramid.includes =
    pyramid_tm
    pyramid_beaker
    pyramid_chameleon
    pyramid_rpc.jsonrpc
    # pyramid_debugtoolbar


session.type = ext:database
session.secret = s0s3cr3ts
session.cookie_expires = true
session.key = WhatEver
session.timeout = 3000
session.lock_dir = %(here)s/tmp
timezone = Asia/Jakarta
;localization = id_ID.UTF-8
#localization = Indonesian_indonesia.1252
localization = English_Australia.1252

# Base Configuration
# temp_files digunakan untuk menyimpan file sementara, seperti hasil export, 
# hasil upload, dll default C:\tmp atau /tmp
temp_files = %(here)s/../tmp

# partner_doc digunakan untuk menyimpan file upload dokumen partner harus permanen, 
# default /tmp/docs/partner/ C:\\tmp\\docs\\partner\\
partner_doc = %(here)s/../tmp/docs/partner/

# Registrasi User
# Digunakan untuk mengatur apakah aplikasi akan menyediakan fitur registrasi user baru,
allow_register = 1
# Template form registrasi, jika kosong akan menggunakan template default dari opensipkd,
reg_form = 
# Digunakan untuk mengatur apakah aplikasi akan meminta input nomor KTP, jika 1
# maka akan muncul field input nomor KTP pada form registrasi,
reg_idcard = 1
# Digunakan untuk mengatur apakah aplikasi akan meminta input nomor Captcha, jika 1
# maka akan muncul field input nomor Captcha pada form registrasi,
reg_captcha = 1
# reg_verify digunakan untuk mengatur apakah aplikasi akan dilakukan verifikasi 
# manual email verifikasi setelah registrasi, jika 1 maka aplikasi akan mengirim 
# email verifikasi ke email yang didaftarkan oleh user,
reg_verify = 1

# Custome template untuk login ke aplikasi
login_tpl =
# Menampilkan captcha pada form login, jika 1 maka akan muncul field input nomor Captcha pada form login,
login_captcha = 1

static_files = %(here)s/../files
captcha_files = %(here)s/../tmp/captcha

;company = Opensipkd
;ibukota = Bekasi
;departement = IT
;address_1 = Jalan....
;address_2 = Bekasi ...
;
;center.phone = 021123456789
;center.mobile = 081311045668
;center.email = aa.gustiana@gmail.com
;center.email_password =
;center.smtp_server =
;
;#_host = http://localhost:5433/demo2
;
;unoconv_py = C:\Program Files\LibreOffice\program\python.exe
;unoconv_bin = C:\product\venv-lates\Scripts\unoconv
;

# `menus` Digunakan  untuk mengatur menu apa saja yang akan ditampilkan pada aplikasi, 
# format menu: url:label atu routekode:label antar menu dipisahkan dengan baris baru, contoh:
; menus = 
;    bphtb:BPHTB
;    five:Five
# Default nama aplikasi
;app_name = OPENSIPKD-APP

# digunakan untuk mengatur apakah user bisa berganti2 dinas
;change_unit = False
;departemen_chg_id = 3

; PROXY Setting tambahan untuk proxy
;trusted_proxy_headers = "forwarded x-forwarded-for x-forwarded-host x-forwarded-proto x-forwarded-port"
;url_prefix='/wsgi'


;[composite:main]
;use = egg:rutter#urlmap
;/ = opensipkd_base
;/wsgi/ = opensipkd_base


;[filter:proxy-prefix]
;use = egg:PasteDeploy#prefix
# digunakan untuk mengatur prefix url jika aplikasi dijalankan di virtual 
# directory, contoh:
# jika aplikasi dijalankan di http://localhost:6543/virdir maka prefix yang digunakan adalah /virdir, 
# jika aplikasi dijalankan di http://localhost:6543/ maka prefix yang digunakan adalah /, 
# jika aplikasi dijalankan di http://localhost:6543/app/ maka prefix yang digunakan adalah /app, dst
;prefix = /virdir

;[pipeline:main]
;pipeline =
;    proxy-prefix
;    opensipkd_base


[server:main]
use = egg:waitress#main
host = 0.0.0.0
port = 6543



[alembic_ziggurat]
script_location = ziggurat_foundations:migrations
sqlalchemy.url = postgresql://aagusti:a@localhost:5432/demo2

[alembic_base]
script_location = opensipkd.base.scripts:alembic
sqlalchemy.url = postgresql://aagusti:a@localhost:5432/demo2

[pytest]
filterwarnings =
    error
    ignore::UserWarning
    ignore:function ham\(\) is deprecated:DeprecationWarning
    
# Begin logging configuration

[loggers]
keys = root, opensipkd, sqlalchemy

[handlers]
keys = console, filelog
#, tabel
[formatters]
keys = generic

[logger_root]
level = WARN
handlers = 
#, tabel

[logger_opensipkd]
level = DEBUG
handlers =console, filelog
qualname = opensipkd

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine
# "level = INFO" logs SQL queries.
# "level = DEBUG" logs SQL queries and results.
# "level = WARN" logs neither.  (Recommended for production systems.)

[handler_filelog]
class = FileHandler
; args = ('log_file','a')
args = ('/tmp/logs/opensipkd.log','a')
level = DEBUG
formatter = generic


[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[handler_tabel]
class = opensipkd.base.handlers.SQLAlchemyHandler
args = ()
level = WARN
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s][%(threadName)s] %(message)s

# End logging configuration
