@startuml uc_users

left to right direction

actor User

rectangle "User Use Case" {
  (Home) as home
  (Password Reset) as passwordReset
  (Change Password) as changePassword
  (Login) as login
  (Logout) as logout
  (Update Profile) as updateProfile
  (Register) as register
}
passwordReset ..> changePassword : extend
changePassword ..> login:include
User -- passwordReset
User -- changePassword
User -- register
User -- login
User -- updateProfile
User -- logout
User -- home


@enduml
